//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metadata
    {
        public string ScreenResolution { get; set; }
        public string Duration { get; set; }
        public string VideoCodec { get; set; }
        public string AudioCodec { get; set; }
        public Nullable<int> FormatId { get; set; }
        public int Id { get; set; }
    }
}
