//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public Nullable<int> MovieId { get; set; }
        public Nullable<bool> Watched { get; set; }
        public string DateWatched { get; set; }
        public int Id { get; set; }
    }
}
