var namespace_stand_alone_framework_test_1_1_stateful_tests_1_1_cache_manager =
[
    [ "CacheMangerTestFixture", "class_stand_alone_framework_test_1_1_stateful_tests_1_1_cache_manager_1_1_cache_manger_test_fixture.html", "class_stand_alone_framework_test_1_1_stateful_tests_1_1_cache_manager_1_1_cache_manger_test_fixture" ],
    [ "Person", "class_stand_alone_framework_test_1_1_stateful_tests_1_1_cache_manager_1_1_person.html", "class_stand_alone_framework_test_1_1_stateful_tests_1_1_cache_manager_1_1_person" ]
];