//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaCentre
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> MetadataId { get; set; }
        public Nullable<int> YearId { get; set; }
        public string Directors { get; set; }
        public string Description { get; set; }
        public Nullable<int> RatingId { get; set; }
        public Nullable<int> GenreId { get; set; }
        public byte[] ThumbnailId { get; set; }
    }
}
